# Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 Open Healthcare Documentation
site_description: Documentation for WSO2 Open Healthcare Accelerator
site_author: WSO2
site_url: https://oh.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/open-healthcare-docs
repo_url: https://github.com/wso2/open-healthcare-docs
edit_uri: https://github.com/wso2/open-healthcare-docs/edit/main-new/en/docs/

# Copyright
copyright: WSO2 Open Healthcare - Documentation

# Configuration
theme: material
theme:
  name: material
  palette:
    primary: deep-orange
    accent: deep-orange
  custom_dir: theme/material
  logo: images/logo.svg
  favicon: images/favicon.png
  highlightjs: true
  feature:
    tabs: true
  language: 'en'

# Navigation
nav:
  - 'Home': index.md
  - 'Get Started':
    - 'What is Open Healthcare': get-started/open-healthcare.md
    - 'WSO2 Open Healthcare Accelerators': get-started/accelerators.md
    - 'Architecturee': get-started/architecture.md
  - 'Install and Setup':
    - 'Deployment Methods': install-and-setup/deployment.md
    - 'Manual Installation': install-and-setup/manual.md
    - 'Deploy on Docker': install-and-setup/deploy-docker.md
    - 'Deploy on Kubernetes': install-and-setup/deploy-kubernetes.md
    - 'Updating the Accelerator': 
      - 'WSO2 Update tool overview': install-and-setup/updates/overview.md
      - 'How to use WSO2 Update tool': install-and-setup/updates/update-tool.md
      - 'How to update OH accelerator': install-and-setup/updates/update-accelerators.md
  - 'Learn':
    - 'FHIR API Definitions': learn/apidefs.md
    - 'FHIR Capability Statement':
      - 'Overview': learn/fhir-capability-statement/overview.md
      - 'Required Features': learn/fhir-capability-statement/required-features.md
    - 'Consent Management':
      - 'Introduction': learn/consent-mgt/intro.md
      - 'Consent Administration': learn/consent-mgt/admin.md
      - 'Consent Requisition': learn/consent-mgt/req.md
      - 'Consent Collection': learn/consent-mgt/collection.md
      - 'Consent Enforcement': learn/consent-mgt/enforcement.md
    - 'FHIR Mappers':
      - 'HL7 To FHIR Overview': learn/fhir-mappers/hl7-to-fhir-overview.md
      - 'HL7 To FHIR: Example': learn/fhir-mappers/hl7-to-fhir-example.md
      - 'HL7 To FHIR References': learn/fhir-mappers/hl7-to-fhir-reference.md
    - 'FHIR Mapping Templates':
      - 'HIR Mapping Templates Overview': learn/fhir-mapping-templates/fhir-mapping-templates-overview.md
      - 'FHIR Mapping Templates Read Example': learn/fhir-mapping-templates/fhir-mapping-templates-example.md
      - 'HIR Mapping Templates Write Example': learn/fhir-mapping-templates/fhir-write-templates-examples
      - 'FHIR Mapping Templates References': learn/fhir-mapping-templates/fhir-mapping-templates-reference.md
    - 'FHIR Connectors': learn/fhir-connectors.md
    - 'SMART On FHIR':
      - 'Well-Known Configuration': learn/smart-on-fhir/wkc.md
      - 'JWT Claims Handling': learn/smart-on-fhir/jwt.md
      - 'How to Get Patient/Member ID': learn/smart-on-fhir/get-patient-id.md
      - 'Tips on Building a SMART Application': learn/smart-on-fhir/tips.md
    - 'EHR/EMR Connector Support': learn/connector.md
    - 'Working with FHIR':
      - 'Overview': learn/smart-on-fhir/wkc.md
      - '1. Building the integration logic': learn/smart-on-fhir/jwt.md
      - '2. Exposing the API': learn/working-with-fhir/exposing-api.md
  - 'Base Scenarios':
      -  'Scenarios': base-scenarios/README.md
  - 'Sample Usecases':
    - 'Patient Access API': use-cases/patient-access.md
    - 'Provider Directory API': use-cases/provider-dir.md
    - 'Database to FHIR': use-cases/db-to-fhir.md
    - 'SMART on FHIR': use-cases/smart-on-fhir.md
    - 'EHR Integration': use-cases/ehr-int.md
  - 'Configurations':
    - 'Email Notifications': configs/email-notifications.md
  - '': page-not-found.md

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - markdown_include.include:
          base_path: docs
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
          base_path: docs
  - pymdownx.tilde

plugins:
    - search
    - markdownextradata: {}

# Extra
extra_css:
  - assets/lib/highlightjs/default.min.css
  - assets/css/theme.css
extra_javascript:
  - assets/lib/highlightjs/highlight.min.js
  - assets/js/theme.js
  - assets/lib/backtotop/js/util.js
  - assets/lib/backtotop/js/main.js
extra:
  social:
    - type: github
      link: https://github.com/wso2
    - type: twitter
      link: https://twitter.com/wso2
    - type: linkedin
      link: https://www.linkedin.com/company/wso2
  site_version: 1.0.0
  base_path: http://localhost:8000
  
  nav_list:
    - Home
    - Get Started
    - Install and Setup
    - Learn
    - Base Scenarios
    - Sample Usecases
    - Configurations